name: Deploy to vfomin.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Setup repo
          uses: actions/checkout@v4


        - name: ssh pipelines
          uses: cross-the-world/ssh-pipeline@master
          with:
            host: 89.223.67.30
            user: root
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            connect_timeout: 10s
            script: |
                cd /var/www/vfomin
                git pull origin main
