name: Deploy to vfomin.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Setup repo
          uses: actions/checkout@v4
        
        - name: Action SSH
          uses: tiyee/action-ssh@release
          with:
            host: 89.223.67.30
            username: root
            privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
            command: |
                cd /var/www/vfomin
                git pull origin main
                # composer install --no-dev
                # php artisan migrate --force
                # sudo systemctl reload php8.0-fpm
