##
name: Deploy to vfomin.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Setup repo
          uses: actions/checkout@v4

        - name: SSH Upload  
          uses: ErenKrt/ssh-push@1.3
          with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              password: ${{ secrets.SSH_PASSWORD }}
              source: "./"
              destination: "/var/tmp/vfomin.zip"
              scripts: |
                cd /var/www/vfomin && git pull -f
              #  rm -rf /var/www/vfomin/*
              #  unzip /var/tmp/vfomin.zip -d /var/www/vfomin
